import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} flex flex-col min-h-screen`}>
        <div className="flex flex-col flex-grow">
          <nav className="bg-blue-600 p-4 text-white">
            <Link className="container mx-auto" href={"/"}>
              <h1 className="text-2xl font-bold tracking-tighter">Personal Finance Visualizer</h1>
            </Link>
          </nav>
          <main className="container mx-auto p-4 flex-grow">{children}</main>
          <footer className="bg-gray-800 p-4 text-white text-center">
            <p>© 2025 Personal Finance Visualizer. All rights reserved.</p>
          </footer>
        </div>
      </body>
    </html>
  );
}